Revert "fix: replace Commands.literal/argument with Brigadier API to fix NoSuchMethodError crash"
This reverts commit c5a99d7bbae9885e794aee55300347333220b071.